puts "🌱 Seeding data..."

w1 = Workout.create(name: "Push")
w2 = Workout.create(name: "Pull")
w3 = Workout.create(name: "Legs")

rs1 = RepAndSet.create(reps: 15, sets: 3)
rs2 = RepAndSet.create(reps: 10, sets: 3)
rs3 = RepAndSet.create(reps: 6, sets: 4)
rs4 = RepAndSet.create(reps: 8, sets: 4)
rs5 = RepAndSet.create(reps: 12, sets: 3)
rs5 = RepAndSet.create(reps: 5, sets: 4)

Exercise.create(name: "Bench Press", muscle: "Chest", exercise_id: 1, workout_id: w1.id, rep_and_set_id: rs1.id)
Exercise.create(name: "Dumbbell Press", muscle: "Chest", exercise_id: 2, workout_id: w1.id, rep_and_set_id: rs3.id)
Exercise.create(name: "Incline Dumbbell Press", muscle: "Chest", exercise_id: 3, workout_id: w1.id, rep_and_set_id: rs5.id)
Exercise.create(name: "Cable Flys", muscle: "Chest", exercise_id: 3, workout_id: w1.id, rep_and_set_id: rs4.id)
Exercise.create(name: "Lat Pulldowns", muscle: "Back", exercise_id: 4, workout_id: w2.id, rep_and_set_id: rs1.id)
Exercise.create(name: "Seated Cable Rows", muscle: "Back", exercise_id: 5, workout_id: w2.id, rep_and_set_id: rs2.id)
Exercise.create(name: "Bent-Over Row", muscle: "Back", exercise_id: 6, workout_id: w2.id, rep_and_set_id: rs2.id)
Exercise.create(name: "V-Bar Pulldown", muscle: "Back", exercise_id: 7, workout_id: w2.id, rep_and_set_id: rs1.id)
Exercise.create(name: "Seated Military Press", muscle: "Shoulders", exercise_id: 8, workout_id: w1.id, rep_and_set_id: rs4.id)
Exercise.create(name: "Lateral Raises", muscle: "Shoulders", exercise_id: 9, workout_id: w1.id, rep_and_set_id: rs2.id)
Exercise.create(name: "Bent-Over Lateral Raises", muscle: "Shoulders", exercise_id: 10, workout_id: w1.id, rep_and_set_id: rs3.id)
Exercise.create(name: "Rear Delt Flys", muscle: "Shoulders", exercise_id: 11, workout_id: w1.id, rep_and_set_id: rs5.id)
Exercise.create(name: "Dumbbell Curls", muscle: "Biceps", exercise_id: 12, workout_id: w2.id, rep_and_set_id: rs5.id)
Exercise.create(name: "Hammer Curls", muscle: "Biceps", exercise_id: 13, workout_id: w2.id, rep_and_set_id: rs3.id)
Exercise.create(name: "EZ Bar Curls", muscle: "Biceps", exercise_id: 16, workout_id: w2.id, rep_and_set_id: rs4.id)
Exercise.create(name: "Cable Tricep Extensions", muscle: "Triceps", exercise_id: 14, workout_id: w1.id, rep_and_set_id: rs1.id)
Exercise.create(name: "Cable Overhead Extension", muscle: "Triceps", exercise_id: 15, workout_id: w1.id, rep_and_set_id: rs1.id)
Exercise.create(name: "Skullcrushers", muscle: "Triceps", exercise_id: 17, workout_id: w1.id, rep_and_set_id: rs2.id)
Exercise.create(name: "Back Squats", muscle: "Legs", exercise_id: 18, workout_id: w3.id, rep_and_set_id: rs2.id)
Exercise.create(name: "Reverse Deadlifts (RDLs)", muscle: "Legs", exercise_id: 19, workout_id: w3.id, rep_and_set_id: rs5.id)
Exercise.create(name: "Leg Press", muscle: "Legs", exercise_id: 20, workout_id: w3.id, rep_and_set_id: rs4.id)
Exercise.create(name: "Hamstring Curls", muscle: "Legs", exercise_id: 21, workout_id: w3.id, rep_and_set_id: rs2.id)
Exercise.create(name: "Leg Extensions", muscle: "Legs", exercise_id: 22, workout_id: w3.id, rep_and_set_id: rs1.id)
Exercise.create(name: "Seated Calf Raises", muscle: "Legs", exercise_id: 23, workout_id: w3.id, rep_and_set_id: rs3.id)
Exercise.create(name: "Bulgarian Split Squats", muscle: "Legs", exercise_id: 24, workout_id: w3.id, rep_and_set_id: rs4.id)
Exercise.create(name: "Standing Calf Raises", muscle: "Legs", exercise_id: 25, workout_id: w3.id, rep_and_set_id: rs5.id)

puts "🌱 Done seeding!"
